---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: boutique
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: frontend

---
apiVersion: v1
kind: Service
metadata:
  name: productcatalogservice
  namespace: boutique
spec:
  ports:
  - port: 3550
    targetPort: 3550
  selector:
    app: productcatalogservice

---
apiVersion: v1
kind: Service
metadata:
  name: cartservice
  namespace: boutique
spec:
  ports:
  - port: 7070
    targetPort: 7070
  selector:
    app: cartservice

---
apiVersion: v1
kind: Service
metadata:
  name: redis-cart
  namespace: boutique
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis-cart

---
apiVersion: v1
kind: Service
metadata:
  name: currencyservice
  namespace: boutique
spec:
  ports:
  - port: 7000
    targetPort: 7000
  selector:
    app: currencyservice

---
apiVersion: v1
kind: Service
metadata:
  name: paymentservice
  namespace: boutique
spec:
  ports:
  - port: 50051
    targetPort: 50051
  selector:
    app: paymentservice

---
apiVersion: v1
kind: Service
metadata:
  name: shippingservice
  namespace: boutique
spec:
  ports:
  - port: 50051
    targetPort: 50051
  selector:
    app: shippingservice

---
apiVersion: v1
kind: Service
metadata:
  name: emailservice
  namespace: boutique
spec:
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: emailservice

---
apiVersion: v1
kind: Service
metadata:
  name: checkoutservice
  namespace: boutique
spec:
  ports:
  - port: 5050
    targetPort: 5050
  selector:
    app: checkoutservice

---
apiVersion: v1
kind: Service
metadata:
  name: recommendationservice
  namespace: boutique
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: recommendationservice

---
apiVersion: v1
kind: Service
metadata:
  name: adservice
  namespace: boutique
spec:
  ports:
  - port: 9090
    targetPort: 9090
  selector:
    app: adservice
